### ISSUE TITLE
Unable to install content pack

### ISSUE THREAD

**Issue by mortenn** [ThoZed/graylog-cp-watchguard#18]
Hello,
I am unable to apply the content pack, using version 0.2 with graylog 2.4.3
Putting the csv files in either /etc/graylog or /etc/graylog/server does not help.

2018-05-22T08:34:58.834+02:00 ERROR [BundleImporter] Error while creating entities in content pack. Starting rollback.
java.lang.IllegalStateException: Configured lookup table <lookup-table-fireware-msg-id-to-name> doesn't exist

**Comment by ThoZed** [comment]
Hello,

just created a new tag for version [**0.3**](https://github.com/ThoZed/graylog-cp-watchguard/releases/tag/0.3) with the latest changes. it should be fine, please give a short feedback.
:-)

**Comment by ThoZed** [comment]
I hope it's the same issue like #17

**Comment by mortenn** [comment]
Just FYI, btw, I filed an rfe with watchguard - FBX-11962: Graylog Extended Log Format (GELF) integration

**Comment by mortenn** [comment]
Aye, 0.3 worked - thanks
