### ISSUE TITLE
Gralog 3.0 (beta)

### ISSUE THREAD

**Issue by morrisads** [ThoZed/graylog-cp-watchguard#26]
Hiya - have you tested this with v3.0 (beta)?  Getting an error 500 when clicking install after importing the first pack:

Error
Installing content pack failed with status: Error: cannot POST http://172.22.114.8:9000/api/system/content_packs/e37b2103-eee3-4b77-bcfd-e3d9957ab79f/0/installations (500). Could not install content pack with ID: e37b2103-eee3-4b77-bcfd-e3d9957ab79f

Cheers

Adam

**Comment by teejayen** [comment]
I'm also receiving the same error when using Graylog 3.0.

**Comment by zshahan** [comment]
Same here.  Any chance for an updated content pack?

**Comment by ThoZed** [comment]
Hey There!
It's good to see that you are interested in running the content pack in Graylog3.0.
Because of compatibility issues with my config i'm actually stuck in 2.x. 

**BUT there will be an release of graylog-cp-watchguard which is capable to run on graylog 3.x.**

Please be patient an feel free to contribute.
Have a nice day!
Cheers
Thomas

**Comment by morrisads** [comment]
Great stuff – thanks Thomas.

Will contribute if we can!

**Comment by manikmakki** [comment]
> Hey There!
> It's good to see that you are interested in running the content pack in Graylog3.0.
> Because of compatibility issues with my config i'm actually stuck in 2.x.
> 
> **BUT there will be an release of graylog-cp-watchguard which is capable to run on graylog 3.x.**
> 
> Please be patient an feel free to contribute.
> Have a nice day!
> Cheers
> Thomas

Hi Thomas! I created 4 PRs for the Content Packs listed. I mostly went through and recreated everything by hand, and as such, there may be something I missed. I had some odd issues with the existing regex, like double or triple backslashes causing Greylog to throw errors, but it all seems to work with my 5 Fireboxes.

**Comment by ThoZed** [comment]
Thanks a lot! manikmakki.

there is a new branch "legacy" to support old versions. your patches are merged in development branch for the upcomming version 0.6... 
Meanwhile everybody with compatibility issues should use the develop branch.
Thanks!
Cheers Thomas
